# This data file was generated by the Spreadsheet Calculator Improvised (SC-IM)
# You almost certainly shouldn't edit it.

let A0 = 1
let A1 = 2
let A2 = 33
let A3 = 44
let A4 = 22
let A5 = 14
let A6 = 4
goto A6
